### ISSUE TITLE
在计算每个user的项目内OpenRank值的构成时，fromNode有可能不存在

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/scripts-for-xlab-ospo-dashboard#1]
4月份数据出炉，于是跑了下脚本，中途遇错：

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/32434520/236494855-86adf325-95ab-46f7-ad50-1853424d3390.png">

目前这么处理了下：

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/32434520/236494945-857ff043-f9e5-4a34-bc4d-aa1b07c789ed.png">

有待搞清楚，可能和导出openrank_details.json时删除了一些结点和边有关，也许要去OpenDigger那提个issue。

**Comment by frank-zsy** [comment]
所有项目都报错还是具体某个项目报错了？

**Comment by tyn1998** [comment]
@frank-zsy 经确认，只有hypercrx在3月份的openrank_details.json缺失了结点：

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/32434520/236600494-2db0b612-65f4-4dec-ae9e-f55ced8be47f.png">

https://oss.x-lab.info/open_digger/github/hypertrons/hypertrons-crx/project_openrank_detail/2023-03.json

<img width="1691" alt="image" src="https://user-images.githubusercontent.com/32434520/236600537-ae5ae8b6-05c0-4c42-b8cf-4ea5838950e4.png">

**Comment by frank-zsy** [comment]
这是一个异常点，ID 154192 对应的节点是这个 Issue https://github.com/hypertrons/hypertrons-crx/issues/636 , 这个 Issue 是 @tyn1998 3.31 23 点提的（北京时间已经是 4 月了），应该是在上个月导入时 3 月的最后一个小时的数据可能还没导入 ClickHouse，导致 Open 事件在计算时还不存在，所以这个节点 3 月的 OpenRank 值是 null，导出时节点过滤掉了，但边没有过滤。

上个月导出时由于还没有导入这个节点所以没问题，但这个月重新导出了 3、4 月的网络，此时已经有了 Open 事件，导致节点被导出了，所以出现了这个问题。

这个月重新导出了 3 月的网络的原因是：3 月加入了人到人的点赞价值转移，如果一个开发者没有给任何人点赞，就认为他给所有人点赞了，这会导致开发者之间几乎是全连通的，在可视化时所有开发者节点会挤在一起，所以这次重新导出时将点赞这部分的边给过滤掉了，以免可视化上不好看的问题。

**Comment by tyn1998** [comment]
@frank-zsy 明白了，感谢分析！
